#!/bin/sh
set -e

if [ "$2" = "hibernate" ] || [ "$2" = "hybrid-sleep" ]; then
    case "$1" in
        pre)
            cat /sys/devices/platform/huawei-wmi/charge_thresholds > /tmp/charge_thresholds
            ;;
    	post)
	    cat /tmp/charge_thresholds > /sys/devices/platform/huawei-wmi/charge_thresholds
	    rm /tmp/charge_thresholds
	    ;;
    esac
fi
